name: 'Soda Core'
description: 'Run Soda Core Scan'
branding:
  icon: 'check-square'  
  color: 'green'

inputs:
  data_source:
    description: 'Data Source name'
    required: true   
    
  configuration:
    description: 'Configuration file'
    required: true    
 
  checks:
    description: 'Checks file'
    required: true    
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.data_source }}
    - ${{ inputs.configuration }}
    - ${{ inputs.checks }}