name: 'Soda Core'
description: 'Run Soda Core Scan'
branding:
  icon: 'check-square'  
  color: 'green'

inputs:
  dataset:
    description: 'Dataset name'
    required: true   
    
  configuration:
    description: 'Configuration file'
    required: true    
 
  days:
    description: 'Test Days'
    required: true    

  checks:
    description: 'Checks file'
    required: true    
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dataset }}
    - ${{ inputs.configuration }}
    - ${{ inputs.days }}
    - ${{ inputs.checks }}
