name: 'Soda SQL'
description: 'Run Soda SQL Scan'
branding:
  icon: 'check-square'  
  color: 'green'

inputs:
  warehouse:
    description: 'Warehouse file'
    required: true   
    
  tests:
    description: 'Tests file'
    required: true    
 
   days:
    description: 'Test Days'
    required: true    
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.warehouse }}
    - ${{ inputs.tests }}
    - ${{ inputs.days }}
